<?php echo $this->doctype(); ?>

<html>
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('Veeam Software Test Task')->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array(
                            'rel' => 'shortcut icon',
                            'type' => 'image/vnd.microsoft.icon',
                            'href' => $this->basePath() . '/img/favicon.ico'
                        ))
                        ->prependStylesheet($this->basePath() . '/css/style.css')
                        ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css') ?>

    </head>
    <body>
        <div class="container">
            <?php echo $this->content; ?>
        </div>
        <?php echo $this->inlineScript() ?>
    </body>
</html>
