<div>
    <?php
        $form = $this->form;
        $form->prepare();

        echo $this->form()->openTag($form);
        echo $this->formRow($form->get('department'));
        echo $this->formRow($form->get('language'));
        echo $this->formSubmit($form->get('submit'));
        echo $this->form()->closeTag();
    ?>
</div>
<table class="table">
    <tr>
        <th>Name</th>
        <th>Description</th>
    </tr>
    <?php foreach ($this->items as $item) : ?>
    <tr>
        <td><?php echo $this->escapeHtml($item->getName());?></td>
        <td><?php echo $this->escapeHtml($item->getDescription());?></td>
    </tr>
    <?php endforeach; ?>
</table>